

export const ROLES = {
  CHA_TUYEN_UY: 'CHA_TUYEN_UY',
  XU_DOAN_TRUONG: 'XU_DOAN_TRUONG',
  TRO_UY_XU_DOAN: 'TRO_UY_XU_DOAN',
  PHO_NOI_VU: 'PHO_NOI_VU',
  PHO_NGOAI_VU: 'PHO_NGOAI_VU',
  TRUONG_NGANH: 'TRUONG_NGANH',
  PHO_NGANH: 'PHO_NGANH',
  TRUONG_BAN: 'TRUONG_BAN',
  PHO_BAN: 'PHO_BAN',
  THANH_VIEN_BAN: 'THANH_VIEN_BAN',
  CHU_NHIEM_LOP: 'CHU_NHIEM_LOP',
  PHU_LOP: 'PHU_LOP'
} as const;

// Nhóm có quyền xem toàn bộ, nhưng KHÔNG có quyền chỉnh sửa
export const ADMIN_VIEW_ROLES = [
  ROLES.CHA_TUYEN_UY,
  ROLES.XU_DOAN_TRUONG,
  ROLES.TRO_UY_XU_DOAN,
  ROLES.PHO_NOI_VU,
  ROLES.PHO_NGOAI_VU,
  ROLES.TRUONG_NGANH,
  ROLES.PHO_NGANH,
] as const;